default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: hdwzc
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: garbage_development

test:
  <<: *default
  database: garbage_test

production:
  <<: *default
  database: garbage_production
  username: root
  password: wzc19931030
  socket: /var/lib/mysql/mysql.sock
